parameter_defaults:
  ControllerCount: 1
  ComputeOvsDpdkCount: 2
  OvercloudControlFlavor: oooq_control
  OvercloudComputeOvsDpdkFlavor: oooq_compute

  #TODO: br-ex needs to be re-looked as nfv ref nic configs does not have br-ex bridge

  # NeutronBridgeMappings translates to neutron::agents::ml2::ovs::bridge_mappings
  NeutronBridgeMappings: "dpdknet:br-link"
  NeutronExternalNetworkBridge: "''"
  # NeutronFlatNetworks translates to neutron::plugins::ml2::flat_networks
  NeutronFlatNetworks: "dpdknet"
  # NeutronNetworkVLANRanges translates to neutron::plugins::ml2::network_vlan_ranges
  # NeutronNetworkVLANRanges: "dpdknet:100:103"
  # NeutronNetworkType translates to neutron::plugins::ml2::tenant_network_types
  NeutronNetworkType: ['vxlan,vlan']
  # NeutronTunnelTypes translates to neutron::agents::ml2::ovs::tunnel_types
  NeutronTunnelTypes: "vxlan"

  #TimeZone: Kolkata
