parameter_defaults:
  ControlPlaneDefaultRoute: "192.168.24.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19', '10.10.160.2']
  EC2MetadataIp: "192.168.24.1"

  ExternalAllocationPools: [{'start': '10.0.0.4', 'end': '10.0.0.250'}]
  ExternalNetCidr: "10.0.0.0/24"
  #ExternalNetworkVlanID: 10
  NeutronExternalNetworkBridge: "''"
  #ExternalInterfaceDefaultRoute: "192.168.24.1"

  InternalApiNetCidr: 10.100.100.0/24
  StorageNetCidr: 10.100.101.0/24
  StorageMgmtNetCidr: 10.100.102.0/24
  TenantNetCidr: 10.100.103.0/24
  InternalApiNetworkVlanID: 100
  StorageNetworkVlanID: 101
  StorageMgmtNetworkVlanID: 102
  TenantNetworkVlanID: 103
  InternalApiAllocationPools: [{'start': '10.100.100.10', 'end': '10.100.100.200'}]
  StorageAllocationPools: [{'start': '10.100.101.10', 'end': '10.100.101.200'}]
  StorageMgmtAllocationPools: [{'start': '10.100.102.10', 'end': '10.100.102.200'}]
  TenantAllocationPools: [{'start': '10.100.103.10', 'end': '10.100.103.200'}]

